EMAIL_ADDRESS = "your_email@gmail.com"
EMAIL_APP_PASSWORD = "your_app_password"

TWILIO_ACCOUNT_SID = "your_account_sid"
TWILIO_AUTH_TOKEN = "your_auth_token"
TWILIO_VERIFY_SERVICE_SID = "your_verify_service_sid"

TELEGRAM_GATEWAY_TOKEN = "your_telegram_gateway_token"
